export const PRESETS = [
  // Board Games (Original Dev Set)
  [
    "Arcs",
    "Root",
    "Oath",
    "Pax Pamir",
    "John Company",
    "Molly House"
  ],
  // The Beatles Studio Albums
  [
    "Please Please Me",
    "With The Beatles",
    "A Hard Day's Night",
    "Beatles for Sale",
    "Help!",
    "Rubber Soul",
    "Revolver",
    "Sgt. Pepper's Lonely Hearts Club Band",
    "Magical Mystery Tour",
    "The Beatles (White Album)",
    "Yellow Submarine",
    "Abbey Road",
    "Let It Be"
  ],
  // Quentin Tarantino Feature Films
  [
    "Reservoir Dogs",
    "Pulp Fiction",
    "Jackie Brown",
    "Kill Bill: Vol. 1",
    "Kill Bill: Vol. 2",
    "Death Proof",
    "Inglourious Basterds",
    "Django Unchained",
    "The Hateful Eight",
    "Once Upon a Time in Hollywood"
  ],
  // 17 Ice Cream Flavors
  [
    "Vanilla",
    "Chocolate",
    "Strawberry",
    "Mint Chocolate Chip",
    "Cookie Dough",
    "Cookies and Cream",
    "Rocky Road",
    "Butter Pecan",
    "Coffee",
    "Pistachio",
    "Neapolitan",
    "Birthday Cake",
    "French Vanilla",
    "Chocolate Chip",
    "Salted Caramel",
    "Moose Tracks",
    "Praline Pecan"
  ],
  // Smash Ultimate Fighters
  [
    "Mario",
    "Donkey Kong",
    "Link",
    "Samus",
    "Dark Samus",
    "Yoshi",
    "Kirby",
    "Fox",
    "Pikachu",
    "Luigi",
    "Ness",
    "Captain Falcon",
    "Jigglypuff",
    "Peach",
    "Daisy",
    "Bowser",
    "Ice Climbers",
    "Sheik",
    "Zelda",
    "Dr. Mario",
    "Pichu",
    "Falco",
    "Marth",
    "Lucina",
    "Young Link",
    "Ganondorf",
    "Mewtwo",
    "Roy",
    "Chrom",
    "Mr. Game & Watch",
    "Meta Knight",
    "Pit",
    "Dark Pit",
    "Zero Suit Samus",
    "Wario",
    "Snake",
    "Ike",
    "Pokemon Trainer (Squirtle)",
    "Diddy Kong",
    "Lucas",
    "Sonic",
    "King Dedede",
    "Olimar",
    "Lucario",
    "R.O.B.",
    "Toon Link",
    "Wolf",
    "Villager",
    "Mega Man",
    "Wii Fit Trainer",
    "Rosalina & Luma",
    "Little Mac",
    "Greninja",
    "Mii Brawler",
    "Mii Swordfighter",
    "Mii Gunner",
    "Palutena",
    "Pac-Man",
    "Robin",
    "Shulk",
    "Bowser Jr.",
    "Duck Hunt",
    "Ryu",
    "Ken",
    "Cloud",
    "Corrin",
    "Bayonetta",
    "Inkling",
    "Ridley",
    "Simon Belmont",
    "Richter",
    "King K. Rool",
    "Isabelle",
    "Incineroar",
    "Piranha Plant",
    "Joker",
    "Hero",
    "Banjo & Kazooie",
    "Terry Bogard",
    "Byleth",
    "Min Min",
    "Steve",
    "Alex",
    "Zombie",
    "Enderman",
    "Sephiroth",
    "Pyra",
    "Mythra",
    "Kazuya",
    "Sora"
  ]
];

export const getRandomPreset = (currentText: string = ''): string[] => {
  // Filter out the current text if it matches a preset exactly, so we get a new one
  const available = PRESETS.filter(p => p.join('\n') !== currentText.trim());

  // If current text matches the only preset (unlikely given multiple presets) or something else, 
  // fall back to random selection from all.
  const pool = available.length > 0 ? available : PRESETS;

  return pool[Math.floor(Math.random() * pool.length)];
};